server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    initialInstanceInfoReplicationIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
security:
  basic:
    enabled: true
  user:
      name: user
      password: password